### ISSUE TITLE
tuning clicks with library si5351 v2.02 and v2.03

### ISSUE THREAD

**Issue by amunters** [amunters/bitx40#1]
tuning clicks with library si5351 v2.02 and v2.03
v2.01 works OK, no clicks/pops from the speaker during tuning

**Comment by protongt** [comment]
can you add smeter for next version? or can you guide me how add it in your coding. i already change to 20x4 lcd display. i want to add smeter reading and swr reading. your's coding i saw very hard for me to make a modification.

**Comment by pavelmc** [comment]
There is a alternative lib here: https://github.com/pavelmc/Si5351mcu that was just updated and tested, it's click noise free while tuning.

I will make a pull request in short.

73 de Pavel CO7WT.

**Comment by amunters** [comment]
Issue has been fixed in the standard SI5351 library v2.05
