### ISSUE TITLE
When upper or lower tuning limits are reached, closing SPOT cause frequency to increase or decrease

### ISSUE THREAD

**Issue by ve3wmb** [amunters/bitx40#5]
In Raduino V1.18 when the upper or lower tuning limit is reached on the tuning pot (i.e. >>>>>> or <<<<<< disappears from display and displayed frequency stops changing), without moving the tuning knob, if the SPOT switch is closed,  the frequency will continue to increment (or decrement) in 1 Hz intervals beyond the limit, until the SPOT switch is released.  This is very minor, but it doesn't seem like the correct behaviour in this situation. My expectation is that "Fine Tune/SPOT" should respect the tuning limits.

**Comment by amunters** [comment]
Thanks for reporting this issue. It's meanwhile fixed since v1.19
73 Allard PE1NWL

**Comment by ve3wmb** [comment]
Thanks Allard. I am curecently out of town but I am looking forward to getting home and trying v1.20.
Cheers
Michael  VE3WMB


Sent from my Galaxy Tab A (2016)-------- Original message --------From: Allard PE1NWL <notifications@github.com> Date: 2017-07-20  4:57 PM  (GMT-04:00) To: amunters/bitx40 <bitx40@noreply.github.com> Cc: Michael Babineau <mbabineau.ve3wmb@gmail.com>, Author <author@noreply.github.com> Subject: Re: [amunters/bitx40] When upper or lower tuning limits are reached,
  closing SPOT cause frequency to increase or decrease (#5) 
Thanks for reporting this issue. It's meanwhile fixed since v1.19

73 Allard PE1NWL

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/amunters/bitx40","title":"amunters/bitx40","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/amunters/bitx40"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amunters in #5: Thanks for reporting this issue. It's meanwhile fixed since v1.19\r\n73 Allard PE1NWL"}],"action":{"name":"View Issue","url":"https://github.com/amunters/bitx40/issues/5#issuecomment-316812870"}}}
